/*
    SPDX-FileCopyrightText: 2026 loteran
    SPDX-License-Identifier: GPL-3.0-or-later

    Strings come from lang/*.ini (Crowdin), not gettext: strings.js is
    generated by scripts/generate_plasmoid_i18n.py. Shared by main.qml
    (Plasma 6) and plasma5.qml, so it sticks to syntax Qt 5 accepts.
*/
.pragma library
.import "strings.js" as Strings

// uiLanguages follows KDE's language setting (LANGUAGE), in preference
// order; a key missing from a translation falls back to English.
function tr(key, args) {
    var text = Strings.strings.en[key] || key;
    var languages = Qt.locale().uiLanguages;
    for (var i = 0; i < languages.length; i++) {
        var lang = languages[i].split("-")[0];
        var table = Strings.strings[lang === "nb" || lang === "nn" ? "no" : lang];
        if (table) {
            text = table[key] || text;
            break;
        }
    }
    for (var name in args || {})
        text = text.replace("{" + name + "}", args[name]);
    return text;
}
