#!/usr/bin/env python3
# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write the Plasma widget's strings.js from the [plasmoid] section of lang/*.ini.

The widget is QML: it cannot use I18n, and Plasma's own i18n() wants gettext
catalogs ASM does not have. So the same Crowdin-managed .ini files are turned
into a JS table at build time. The output is not committed — Crowdin pushes
.ini updates on their own, and a checked-in copy would lag behind them.

Run by every packaging path before installing the widget.
"""
from __future__ import annotations

import configparser
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'src'))

from arctis_sound_manager.lang_sanitize import sanitize_ini_text  # noqa: E402

LANG_DIR = ROOT / 'src' / 'arctis_sound_manager' / 'lang'
OUTPUT = (ROOT / 'src' / 'arctis_sound_manager' / 'desktop' / 'plasmoid'
          / 'contents' / 'ui' / 'strings.js')
SECTION = 'plasmoid'


def collect(lang_dir: Path = LANG_DIR) -> dict[str, dict[str, str]]:
    strings: dict[str, dict[str, str]] = {}
    for path in sorted(lang_dir.glob('*.ini')):
        parser = configparser.RawConfigParser()
        try:
            parser.read_string(sanitize_ini_text(path.read_text(encoding='utf-8')),
                               source=str(path))
        except (OSError, configparser.Error) as e:
            # Same as the app: one broken translation falls back to English
            # rather than failing the build.
            print(f'skipping {path.name}: {e}', file=sys.stderr)
            continue
        if parser.has_section(SECTION):
            values = {k: v for k, v in parser[SECTION].items() if v.strip()}
            if values:
                strings[path.stem] = values
    return strings


def render(strings: dict[str, dict[str, str]]) -> str:
    return ('// Generated by scripts/generate_plasmoid_i18n.py from lang/*.ini'
            ' — do not edit.\n'
            '.pragma library\n\n'
            f'var strings = {json.dumps(strings, ensure_ascii=False, indent=1, sort_keys=True)};\n')


def main() -> int:
    strings = collect()
    if 'en' not in strings:
        print(f'no [{SECTION}] section in en.ini', file=sys.stderr)
        return 1
    OUTPUT.write_text(render(strings), encoding='utf-8')
    print(f'{OUTPUT.relative_to(ROOT)}: {len(strings)} languages')
    return 0


if __name__ == '__main__':
    sys.exit(main())
